import { createClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";
import Link from "next/link";
import Nav from "@/components/Nav";
import AddUserModal from "./AddUserModal";
import RegistrationApproval from "./RegistrationApproval";
import RealtimeRefresh from "@/components/RealtimeRefresh";
import { TOTAL_OBJECTIVES } from "@/lib/progress";

export default async function AdminPage(){
 const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");const {data:profile}=await supabase.from("profiles").select("*").eq("id",user.id).single();if(profile?.role!=="admin"||profile.status!=="active")redirect("/dashboard");
 const {data:users}=await supabase.from("profiles").select("id,role,status,department");const people=users??[];const employees=people.filter(u=>u.role==="employee");const managedPeople=people.filter(u=>u.role!=="admin");const pendingUsers=people.filter(u=>u.status==="pending").length;const activeUsers=employees.filter(u=>u.status==="active").length;
 const [{count:pendingPER},{data:objectives},{data:exams}]=await Promise.all([supabase.from("per_objectives").select("id",{count:"exact",head:true}).eq("status","pending_approval"),supabase.from("per_objectives").select("user_id,status"),supabase.from("exams").select("user_id,status,result")]);
 const employeeIds=new Set(employees.map(e=>e.id));const approved=objectives?.filter(o=>employeeIds.has(o.user_id)&&o.status==="approved").length??0;const globalProgress=employees.length?Math.round((approved/(employees.length*TOTAL_OBJECTIVES))*100):0;
 const departmentIds=new Map<string,string>();for(const e of employees)if(e.department)departmentIds.set(e.id,e.department);const deptTotals:Record<string,{total:number;passed:number}>={};for(const e of employees)if(e.department)deptTotals[e.department]??={total:0,passed:0};for(const exam of exams??[]){const dept=departmentIds.get(exam.user_id);if(!dept)continue;deptTotals[dept].total++;if(exam.result==="passed"||exam.status==="passed")deptTotals[dept].passed++;}
 const passRates=Object.entries(deptTotals).map(([department,v])=>({department,rate:v.total?Math.round(v.passed/v.total*100):0})).sort((a,b)=>b.rate-a.rate).slice(0,6);
 return <div><RealtimeRefresh/><Nav role="admin" name={`${profile.first_name??""} ${profile.last_name??""}`}/><main className="max-w-7xl mx-auto px-6 lg:px-10 py-8"><section className="flex flex-col md:flex-row md:items-end md:justify-between gap-6 mb-8"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-primary">Administration</p><h1 className="text-3xl font-extrabold text-on-surface mt-2">User Management</h1><p className="text-sm text-on-surface-variant mt-2 max-w-2xl">Manage access levels, monitor progress, and oversee professional development across the organization.</p></div><div className="flex gap-2"><Link href="/employees" className="inline-flex items-center px-5 py-3 rounded-lg border border-outline-variant text-sm font-semibold hover:bg-surface-container">View People</Link><AddUserModal/></div></section>
 <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-8"><AdminStatCard label="Total Employees" value={employees.length}/><div className="bg-surface-container-lowest border border-outline-variant rounded-xl p-5 flex flex-col items-center justify-center"><div className="relative w-20 h-20"><svg className="w-full h-full -rotate-90"><circle cx="40" cy="40" r="34" fill="transparent" stroke="currentColor" className="text-surface-container" strokeWidth="8"/><circle cx="40" cy="40" r="34" fill="transparent" stroke="currentColor" className="text-primary" strokeWidth="8" strokeDasharray="213" strokeDashoffset={213-(213*globalProgress/100)} strokeLinecap="round"/></svg><span className="absolute inset-0 flex items-center justify-center font-bold text-on-surface">{globalProgress}%</span></div><p className="text-xs font-bold uppercase tracking-wide text-on-surface-variant mt-3">Global Progress</p></div><AdminStatCard label="Active Employees" value={activeUsers}/><AdminStatCard label="Pending Signups" value={pendingUsers}/></section>
 <section className="bg-surface-container-lowest border border-outline-variant rounded-xl p-5 mb-8"><div className="flex items-center justify-between mb-5"><div><p className="text-xs font-bold uppercase tracking-wide text-on-surface-variant">Department performance</p><h2 className="text-lg font-bold text-on-surface mt-1">Pass Rates by Department</h2></div><Link href="/reports" className="text-xs font-semibold text-primary hover:underline">View reports →</Link></div>{passRates.length===0?<p className="text-sm text-on-surface-variant">No exam results are available yet.</p>:<div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-5">{passRates.map(item=><div key={item.department}><div className="h-24 bg-surface-container rounded-md flex items-end overflow-hidden"><div className="w-full bg-primary rounded-t-md" style={{height:`${Math.max(item.rate,4)}%`}}/></div><p className="text-xs font-semibold mt-2 truncate" title={item.department}>{item.department}</p><p className="text-xs text-on-surface-variant">{item.rate}% passed</p></div>)}</div>}</section>
 <RegistrationApproval/><section className="bg-surface-container-lowest border border-outline-variant rounded-xl p-5 mt-6"><h2 className="text-lg font-bold text-on-surface">Administration</h2><p className="text-sm text-on-surface-variant mt-1 mb-5">Manage access, branding, people actions and reporting from the dedicated areas.</p><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-3"><AdminLink href="/admin/roles" title="Roles & Access" description="Manage roles and departments." primary/><AdminLink href="/admin/branding" title="Branding" description="Upload the TC Professional Services logo."/><AdminLink href="/employees" title="People" description={`Search and manage ${managedPeople.length} employees and managers.`}/><AdminLink href="/approvals" title={`PER Approvals (${pendingPER??0})`} description="Review submitted PER objectives."/><AdminLink href="/reports" title="Reports" description="View PER and exam reporting."/></div></section></main></div>;
}
function AdminStatCard({label,value}:{label:string;value:number}){return <div className="bg-surface-container-lowest border border-outline-variant rounded-xl p-5"><p className="text-xs font-bold uppercase tracking-wide text-on-surface-variant mb-1">{label}</p><p className="text-3xl font-extrabold text-primary">{value}</p></div>}
function AdminLink({href,title,description,primary=false}:{href:string;title:string;description:string;primary?:boolean}){return <Link href={href} className={`rounded-lg border p-4 transition hover:-translate-y-0.5 ${primary?"border-primary bg-primary text-on-primary":"border-outline-variant bg-surface-container-lowest"}`}><p className="text-sm font-semibold">{title}</p><p className={`text-xs mt-1 ${primary?"opacity-90":"text-on-surface-variant"}`}>{description}</p></Link>}
