"use client";

import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import Nav from "@/components/Nav";

const MAX_IMAGE_SIZE = 50 * 1024;
const ALLOWED_IMAGE_TYPES = ["image/jpeg", "image/png", "image/webp"];
const TOTAL_OBJECTIVES = 22;

type Profile = { id: string; first_name: string; last_name: string; email: string; role: string; department: string | null; job_title: string | null; phone: string | null; joining_date: string | null; avatar_url: string | null; status: string; last_login: string | null; per_objective_number: string | null };
type Department = { name: string; is_active: boolean };

export default function ProfilePage() {
  const supabase = createClient();
  const [profile, setProfile] = useState<Profile | null>(null); const [departments, setDepartments] = useState<Department[]>([]);
  const [perCount, setPerCount] = useState(0); const [pendingPerCount, setPendingPerCount] = useState(0);
  const [form, setForm] = useState({ first_name: "", last_name: "", phone: "", department: "", job_title: "", joining_date: "", avatar_url: "", per_objective_number: "" });
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [uploading, setUploading] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);

  useEffect(() => { (async () => {
    const { data: { user } } = await supabase.auth.getUser(); if (!user) { window.location.href = "/login"; return; }
    const [{ data, error }, { data: departmentData }, { data: objectiveData }] = await Promise.all([
      supabase.from("profiles").select("*").eq("id", user.id).single(),
      supabase.from("departments").select("name,is_active").eq("is_active", true).order("name"),
      supabase.from("per_objectives").select("status").eq("user_id", user.id),
    ]);
    if (error) { setError(error.message); setLoading(false); return; }
    const objectives = objectiveData ?? [];
    setProfile(data as Profile); setDepartments((departmentData ?? []) as Department[]); setPerCount(objectives.filter((o) => o.status === "approved").length); setPendingPerCount(objectives.filter((o) => o.status === "pending_approval").length);
    setForm({ first_name: data.first_name ?? "", last_name: data.last_name ?? "", phone: data.phone ?? "", department: data.department ?? "", job_title: data.job_title ?? "", joining_date: data.joining_date ?? "", avatar_url: data.avatar_url ?? "", per_objective_number: data.per_objective_number ?? "" }); setLoading(false);
  })(); }, []);

  const save = async (event: React.FormEvent) => { event.preventDefault(); if (!profile) return; setSaving(true); setError(null); setMessage(null); const firstName = form.first_name.trim(); const lastName = form.last_name.trim(); if (!firstName || !lastName) { setSaving(false); setError("First name and last name are required."); return; } const { data, error: updateError } = await supabase.from("profiles").update({ first_name: firstName, last_name: lastName, phone: form.phone.trim() || null, department: form.department || null, job_title: form.job_title.trim() || null, joining_date: form.joining_date || null, avatar_url: form.avatar_url || null, per_objective_number: form.per_objective_number.trim() || null }).eq("id", profile.id).select("*").single(); setSaving(false); if (updateError) { setError(updateError.message); return; } setProfile(data as Profile); setMessage("Profile updated successfully."); };
  const handleImage = async (file?: File) => { setError(null); setMessage(null); if (!file || !profile) return; if (file.size > MAX_IMAGE_SIZE) { setError("Profile image must be 50 KB or smaller."); return; } if (!ALLOWED_IMAGE_TYPES.includes(file.type)) { setError("Please select a JPG, PNG or WEBP image."); return; } setUploading(true); const extension = file.type === "image/jpeg" ? "jpg" : file.type === "image/png" ? "png" : "webp"; const path = `${profile.id}/avatar.${extension}`; const { error: uploadError } = await supabase.storage.from("profile-images").upload(path, file, { upsert: true, contentType: file.type, cacheControl: "3600" }); if (uploadError) { setUploading(false); setError(`Image upload failed: ${uploadError.message}`); return; } const { data } = supabase.storage.from("profile-images").getPublicUrl(path); const avatarUrl = `${data.publicUrl}?v=${Date.now()}`; const { error: updateError } = await supabase.from("profiles").update({ avatar_url: avatarUrl }).eq("id", profile.id); setUploading(false); if (updateError) { setError(`Image uploaded but profile could not be updated: ${updateError.message}`); return; } setForm((value) => ({ ...value, avatar_url: avatarUrl })); setProfile((value) => value ? { ...value, avatar_url: avatarUrl } : value); setMessage("Profile image updated successfully."); };
  const removeImage = async () => { if (!profile || !form.avatar_url) return; setUploading(true); setError(null); setMessage(null); const paths = ["jpg", "png", "webp"].map((ext) => `${profile.id}/avatar.${ext}`); const { error: removeError } = await supabase.storage.from("profile-images").remove(paths); if (removeError) { setUploading(false); setError(`Unable to remove image: ${removeError.message}`); return; } const { error: updateError } = await supabase.from("profiles").update({ avatar_url: null }).eq("id", profile.id); setUploading(false); if (updateError) { setError(updateError.message); return; } setForm((value) => ({ ...value, avatar_url: "" })); setProfile((value) => value ? { ...value, avatar_url: null } : value); setMessage("Profile image removed."); };

  if (loading) return <main className="p-8 text-sm text-on-surface-variant">Loading profile...</main>;
  if (!profile) return <main className="p-8 text-sm text-error">Unable to load profile.</main>;
  const departmentOptions = [...departments.map((department) => department.name), ...(form.department && !departments.some((department) => department.name === form.department) ? [form.department] : [])];
  const perProgress = Math.min(100, Math.round((perCount / TOTAL_OBJECTIVES) * 100));

  return <div><Nav role={profile.role} name={`${profile.first_name ?? ""} ${profile.last_name ?? ""}`.trim()} /><main className="max-w-4xl mx-auto px-4 sm:px-6 py-6 sm:py-8"><div className="mb-6"><h1 className="text-2xl font-bold text-on-surface">My Profile</h1><p className="text-sm text-on-surface-variant mt-1">Keep your professional information and PER reference up to date.</p></div>
    <section className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6"><ProfileStat label="PER Objectives Approved" value={`${perCount} / ${TOTAL_OBJECTIVES}`} detail={`${perProgress}% complete`} /><ProfileStat label="Pending PER" value={pendingPerCount} detail="Awaiting approval" /><ProfileStat label="PER Objective Number" value={profile.per_objective_number || "—"} detail="Employee-maintained reference" /></section>
    <form onSubmit={save} className="bg-surface-container-lowest border border-outline-variant rounded-xl p-5 sm:p-6 space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center gap-4"><div className="w-20 h-20 rounded-full border border-outline-variant overflow-hidden bg-surface-container flex items-center justify-center shrink-0">{form.avatar_url ? <img src={form.avatar_url} alt="Profile" className="w-full h-full object-cover" /> : <span className="text-xl font-bold text-primary">{form.first_name?.[0] ?? "?"}</span>}</div><div><label className="text-sm font-semibold text-on-surface">Profile image</label><input type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={(event) => handleImage(event.target.files?.[0])} className="block text-xs mt-2" /><p className="text-[11px] text-on-surface-variant mt-1">JPG, PNG or WEBP · maximum 50 KB.</p>{form.avatar_url && <button type="button" onClick={removeImage} disabled={uploading} className="text-xs font-medium text-error hover:underline mt-2 disabled:opacity-50">Remove image</button>}</div></div>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><Field label="First name" value={form.first_name} onChange={(value) => setForm({ ...form, first_name: value })} required /><Field label="Last name" value={form.last_name} onChange={(value) => setForm({ ...form, last_name: value })} required /><Field label="Phone" value={form.phone} onChange={(value) => setForm({ ...form, phone: value })} /><Field label="Job title" value={form.job_title} onChange={(value) => setForm({ ...form, job_title: value })} /><div><label className="block text-xs font-semibold text-on-surface-variant mb-1">Department</label><select value={form.department} onChange={(event) => setForm({ ...form, department: event.target.value })} className="w-full border border-outline-variant rounded-md px-3 py-2 text-sm bg-background"><option value="">Select department</option>{departmentOptions.map((department) => <option key={department} value={department}>{department}</option>)}</select><p className="text-[11px] text-on-surface-variant mt-1">Options are managed by Admin → Roles & Access.</p></div><div><label className="block text-xs font-semibold text-on-surface-variant mb-1">Joining date</label><input type="date" value={form.joining_date} onChange={(event) => setForm({ ...form, joining_date: event.target.value })} className="w-full border border-outline-variant rounded-md px-3 py-2 text-sm bg-background" /></div><Field label="PER Objective Number" value={form.per_objective_number} onChange={(value) => setForm({ ...form, per_objective_number: value })} /></div>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><Field label="Email" value={profile.email ?? ""} onChange={() => {}} disabled /><Field label="Role" value={profile.role ?? ""} onChange={() => {}} disabled /><Field label="Account status" value={profile.status ?? ""} onChange={() => {}} disabled /><Field label="Last login" value={profile.last_login ? new Date(profile.last_login).toLocaleString() : "Not available"} onChange={() => {}} disabled /></div>
      {uploading && <p className="text-sm text-on-surface-variant bg-surface-container rounded-md p-3">Updating profile image...</p>}{error && <p className="text-sm text-error bg-error-container/40 border border-error/30 rounded-md p-3">{error}</p>}{message && <p className="text-sm text-on-surface-variant bg-surface-container rounded-md p-3">{message}</p>}<button disabled={saving || uploading} className="bg-primary text-on-primary rounded-md px-5 py-2 text-sm font-semibold disabled:opacity-50">{saving ? "Saving..." : "Save profile"}</button>
    </form></main></div>;
}
function ProfileStat({ label, value, detail }: { label: string; value: string | number; detail: string }) { return <div className="bg-surface-container-lowest border border-outline-variant rounded-xl p-5"><p className="text-xs font-bold uppercase tracking-wide text-on-surface-variant">{label}</p><p className="text-2xl font-extrabold text-primary mt-2">{value}</p><p className="text-xs text-on-surface-variant mt-1">{detail}</p></div>; }
function Field({ label, value, onChange, required = false, disabled = false }: { label: string; value: string; onChange: (value: string) => void; required?: boolean; disabled?: boolean }) { return <div><label className="block text-xs font-semibold text-on-surface-variant mb-1">{label}</label><input required={required} disabled={disabled} value={value} onChange={(event) => onChange(event.target.value)} className="w-full border border-outline-variant rounded-md px-3 py-2 text-sm bg-background disabled:opacity-60" /></div>; }
