"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

type Profile={id:string;first_name:string|null;last_name:string|null;email:string|null;department:string|null;joining_date?:string|null};
export default function AdminProfileActions({profile}:{profile:Profile}){
 const router=useRouter(); const supabase=createClient(); const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false);
 const [firstName,setFirstName]=useState(profile.first_name??""); const [lastName,setLastName]=useState(profile.last_name??""); const [department,setDepartment]=useState(profile.department??""); const [joiningDate,setJoiningDate]=useState(profile.joining_date??""); const [error,setError]=useState<string|null>(null);
 const save=async()=>{setSaving(true);setError(null);const {error}=await supabase.from("profiles").update({first_name:firstName.trim(),last_name:lastName.trim(),department:department.trim()||null,joining_date:joiningDate||null}).eq("id",profile.id);setSaving(false);if(error){setError(error.message);return;}setOpen(false);router.refresh();};
 const remove=async()=>{if(!window.confirm(`Are you sure you want to delete ${profile.first_name??"this employee"} ${profile.last_name??""}'s profile? This cannot be undone.`))return;setSaving(true);const {error}=await supabase.from("profiles").delete().eq("id",profile.id);setSaving(false);if(error){setError(error.message);return;}router.push("/employees");router.refresh();};
 return <><div className="flex gap-2"><button type="button" onClick={()=>setOpen(true)} className="rounded-md border border-outline-variant px-2.5 py-1.5 text-xs font-semibold">Edit</button><button type="button" onClick={remove} disabled={saving} className="rounded-md border border-error/40 text-error px-2.5 py-1.5 text-xs font-semibold disabled:opacity-50">Delete</button></div>{open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="w-full max-w-lg rounded-xl bg-surface-container-lowest border border-outline-variant p-6"><div className="flex justify-between mb-5"><h2 className="text-lg font-bold">Edit employee profile</h2><button onClick={()=>setOpen(false)} aria-label="Close">×</button></div><div className="grid grid-cols-2 gap-4"><label className="text-xs font-semibold">First name<input value={firstName} onChange={e=>setFirstName(e.target.value)} className="mt-1 w-full rounded-md border border-outline-variant px-3 py-2 text-sm"/></label><label className="text-xs font-semibold">Last name<input value={lastName} onChange={e=>setLastName(e.target.value)} className="mt-1 w-full rounded-md border border-outline-variant px-3 py-2 text-sm"/></label><label className="text-xs font-semibold">Department<input value={department} onChange={e=>setDepartment(e.target.value)} className="mt-1 w-full rounded-md border border-outline-variant px-3 py-2 text-sm"/></label><label className="text-xs font-semibold">Joining date<input type="date" value={joiningDate} onChange={e=>setJoiningDate(e.target.value)} className="mt-1 w-full rounded-md border border-outline-variant px-3 py-2 text-sm"/></label></div>{error&&<p className="mt-4 text-xs text-error">{error}</p>}<div className="mt-6 flex justify-end gap-2"><button onClick={()=>setOpen(false)} className="rounded-md border border-outline-variant px-4 py-2 text-sm">Cancel</button><button onClick={save} disabled={saving} className="rounded-md bg-primary text-on-primary px-4 py-2 text-sm font-semibold">{saving?"Saving...":"Save changes"}</button></div></div></div>}</>;
}